### ISSUE TITLE
Docker image with redhat

### ISSUE THREAD

**Issue by andrewleith** [drupalwxt/wxt#199]
Hi - we have a redhat server here and would like to try using WXT.  What is the appropriate install mechanism in this case? Can we use docker to do this? Which guide should we follow?

Thanks,
Andrew

**Comment by sylus** [comment]
Hi there @andrewleith So there are three ways:

a) If you have RedHat OpenShift: I would use https://github.com/drupalwxt/helm-drupal (see the docs folder for more info)
b) If you have regular RedHat and just want to use docker can just take a look at our scaffold: https://github.com/drupalwxt/docker-scaffold (just calls docker-compose)
c) You can just use the regular composer method also if don't want to use docker.

If interested and wanted to see this in action, our CI actually uses docker for its internal testing:

https://travis-ci.org/drupalwxt/site-wxt/jobs/646236461#L2826 (docker-compose up)
https://travis-ci.org/drupalwxt/site-wxt/jobs/646236461#L2827 (docker-compose ps)

If you have Azure Cloud and don't want to use Kubernetes can also just run the containers themselves using the Azure Web App service which simply calls docker-compose under the scenes:

https://github.com/drupalwxt/terraform-containers-webapp-azure/blob/master/config/docker-compose.yml (I used a managed db rather then in container)

For running in production you really only need the following 2 containers:

https://hub.docker.com/r/drupalwxt/site-wxt/tags (3.0.7 and 3.0.7-nginx)

Note: We have two since we might want to scale nginx seperately from php-fpm.

**Comment by andrewleith** [comment]
Thanks for the quick reply.  We have an on-prem redhat server - I'll try option b above and see where that takes me.

Thanks,
Andrew

**Comment by sylus** [comment]
This compose  file is prolly the most relevant to you sine uses pre built images: 

https://github.com/drupalwxt/terraform-containers-webapp-azure/blob/master/config/docker-compose.yml
