### ISSUE TITLE
Make workflow/moderation configs optional

### ISSUE THREAD

**Issue by ergonlogic** [drupalwxt/wxt#222]
We have built a site using WXT as a base profile. However, we are not using the workflow or moderation features from WxT and/or Lightning. As such, we disable them in our profile. The recent introduction of a couple configs under `config/install` is now making install fail with:

>\[Drupal\\Core\\Config\\UnmetDependenciesException\]  
>Configuration objects provided by *wxt* have unmet dependencies: *views.view.content (content_moderation), workflows.workflow.editorial (node.type.landing_page, node.type.page, content_moderation, work  
>flows)*

Moving these configs (`views.view.content`, `workflows.workflow.editorial`) into `config/optional` resolves the issue on our part. Presumably, it should still make them available when the relevant modules are enabled.

**Comment by sylus** [comment]
@nathanpw why were these moved out of config/optional?

**Comment by nathanpw** [comment]
Can we move this issue to d.o? Those configs were moved due to this.: https://www.drupal.org/project/config_rewrite/releases/8.x-1.2 in v3.0.12. Can you provide the version and steps to recreate the error you mention above? I am pretty sure removing this will break the default admin/content view and workflow settings. I also vaguely remember introducing a fix to this after 3.0.12 (but can't remember exactly what it was right now). Have you tried against the latest wxt code base?

https://github.com/drupalwxt/wxt/commit/3366aaee6f4a05828d6f12ae2f1a4c132402c1e3
