### ISSUE TITLE
Drupal 10

### ISSUE THREAD

**Issue by markwooff** [drupalwxt/wxt#292]
Good morning! First off, our team is very grateful for all the work done in this DrupalWxT repo to ensure CVEs are patched and update are made to the core files. Updating our CI/CD pipelines by incrementing the  `drupalwxt/site-wxt:X.X.X` docker builds really makes things easy to use.

That being said, are there any plans on upgrading to Drupal 10? I know it only came out recently but was curious if there was a roadmap for getting to it. Thanks!

**Comment by auxonic** [comment]
Just seeing a new [WxT 5.0.x-dev](https://packagist.org/packages/drupalwxt/wxt#5.0.x-dev) build on packagist that's using core 10.0.4.  From running plain Drupal 10 on my personal blog I can say it's doing well, but a lot of modules are missing support.

The team is definitely working on it.

I've just about got my department's five D9 sites up to the current build.  A couple were stuck back on versions using Lightning.  Lots of little things have changed.  For new sites the fresh install route yeilds a much cleaner site but things are upgradable.

**Comment by smulvih2** [comment]
Hey @auxonic, yes I have created a 5.0.x-dev branch to start testing the D10 upgrade. It is still a work in progress. You can follow progress here - [https://www.drupal.org/project/wxt/issues/3338699](https://www.drupal.org/project/wxt/issues/3338699)

**Comment by auxonic** [comment]
Great work!  Thanks

**Comment by sylus** [comment]
Yup work is on going for this, I think it is probably still about a month out as there is a lot of work with the modules and in particular CKEditor itself.

**Comment by markwooff** [comment]
Thanks for the update @sylus - as always, we really appreciate the work you and the team does in this repo. Will keep contributing back as much as possible on our end.

**Comment by rgalipeau** [comment]
Note that you can always downgrade from CK5 to CK4 in DrupalWxT 10, as we are planning for several fed gov builds …until the Ckeditor5 modules and plugins mature in Drupal.

**Comment by joejoseph00** [comment]
Hi folks, chomping at the bit here putting 5.0.x through it's paces.  I've upgraded a wxt site from 4.3.0 to 4.5.3 (my own special sauce to do that) then on to 5.0.x , lots is working, but I'm stumped on the node edit save draft

I'm seeing this error:
`Entity queries must explicitly set whether the query should be access checked or not. See Drupal\Core\Entity\Query\QueryInterface::accessCheck().`

it's easy enough to fix but hard to find out which module is at the origin of this?  tried devel backtrace but short on clues.

I've uninstalled our custom modules to make sure they're not causing the problem, uninstalled a bunch of contrib modules we were using but it seems that there's possibly something wxt involved however I have no evidence of this just guessing, I'll have to dig more.  I've openned a thread on **d10readiness** in the **drupal.slack.com** to see if I get any helpful suggestions.  With that said, contrib is in pretty good shape for D10, it's time to make this happen.

I guess the reason why I'm posting this is because I seem to recall the vanilla install having the same issue saving a draft node also, so it might be either a contrib dependency of wxt or wxt it'self.

**Comment by joejoseph00** [comment]
Update, some friendly folks on drupal.slack.com d10readiness channel suggested using the drupal-check utility.
https://drupalize.me/blog/jump-start-your-drupal-9-code-updates-drupal-check-and-drupal-rector

**Comment by joejoseph00** [comment]
running this command now to see which contrib module might be the culprit:

`vendor/bin/drupal-check --no-progress /var/www/my-wxt-site/docroot/html/modules/contrib/ > drupal-check-deprecations-report.txt`

**Comment by joejoseph00** [comment]
ok so that didn't help but some guessing did (uninstalled suspected culprit),  I ended up finding that it was one of my lesser known contrib modules causing the issue, using upgrade_status drush command to help fix it.
example from Drupal 9 environment:
```
composer require drupal/upgrade_status;
drush en upgrade_status;
drush upgrade_status:analyze my_special_module_name
```

**Comment by sylus** [comment]
Just going to close this issue but it looks like we are 1-2 weeks away from publishing an initial D10 release. :)

**Comment by joejoseph00** [comment]
Yes we're well on our way for 5.0.0 , it's working extremely well , in our case we've opted to use ckeditor 4 with 5.0.x for the time being, we'll look to move to ck5 once the embed_block module is fully functional with ck5.  I'm not sure what the call will be on the wxt side but for us, ck4 is going to get us into D10 for now
